---
- name: enable epel
  yum:
    #name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    name: epel-release
    state: present

- name: install docker-compose requirements
  yum:
    name: python-pip
    state: present
  tags: [ 'packages' ]

- name: install docker-compose
  pip:
    name: docker-compose
    state: present
  tags: [ 'packages' ]
