---
# vars file for apache
apache_daemon: httpd
apache_daemon_path: /usr/sbin
apache_server_root: /etc/httpd
apache_conf_path: "{{ apache_server_root }}/conf.d"

apache_packages:
  - httpd

apache_ports_configuration:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
    }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
    }
