---
- import_playbook: master_app.yml

- hosts: [database]
  become: true
  gather_facts: false
  tasks:
    - name: update yum cache
      yum: name=* state=latest update_cache=yes
      tags: [ 'packages' ]

- import_playbook: database.yml