---
- hosts: jenkins
  # get privilege
  become: true
  roles:
    - java
    - git
    - role: apache
      apache_vhosts:
        - servername: "jenkins.parisot.xyz"
          path: /
          proxyport: 8080
    - jenkins