---
- hosts: control
  # get privilege
  become: true
  roles:
    - role: ec2
      group: database
      security_rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0