---
- hosts: webserver
  # get privilege
  become: true
  roles:
    - role: java
      open_jdk: True
    - role: apache
      apache_vhosts:
        - servername: "app.parisot.xyz"
          path: /
          proxyport: 8080
    - application