---
- name: create data volume
  file:
    path: "{{ volume_jfrog }}/{{ artifactory_name}}/data"
    state: directory

- name: create logs volume
  file:
    path: "{{ volume_jfrog }}/{{ artifactory_name}}/logs"
    state: directory

- name: create etc volume
  file:
    path: "{{ volume_jfrog }}/{{ artifactory_name}}/etc"
    state: directory

- name: launch artifactory
  docker_container:
    name: "{{ artifactory_docker_name }}"
    image: "{{ artifactory_docker_image }}:{{ artifactory_docker_image_version }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ volume_jfrog }}/{{ artifactory_name}}/data:/var/opt/jfrog/artifactory/data"
      - "{{ volume_jfrog }}/{{ artifactory_name}}/logs:/var/opt/jfrog/artifactory/logs"
      - "{{ volume_jfrog }}/{{ artifactory_name}}/etc:/var/opt/jfrog/artifactory/etc"
    ports:
      - "{{ artifactory_port }}:8081"