---
- name: install artifactory service
  yum:
    name: "https://bintray.com/artifact/download/jfrog/artifactory-rpms/artifactory-{{ artifactory_version }}.rpm"
    state: present

- name: enable artifactory service
  service: name=artifactory enabled=yes

- name: start artifactory service
  service: name=artifactory state=started